/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  bryanSidebar: { // Change this to a more appropriate name, e.g., "bryanSidebar"
    "Bryan's Blueprint": [
      'bryan/intro',
      {
        type: 'category',
        label: 'Sleep',
        items: [
          'bryan/sleep/overview',
          {
            type: 'category',
            label: 'Morning',
            items: [
              'bryan/sleep/Morning/overview',
            ]
          },
          {
            type: 'category',
            label: 'Evening',
            items: [
              'bryan/sleep/Evening/overview',
              'bryan/sleep/Evening/wind-down-routine',
              'bryan/sleep/Evening/evening-skin-care-routine',
              'bryan/sleep/Evening/sleep-environment',
              'bryan/sleep/Evening/going-to-sleep',
            ],
          },
        ]
      },
      {
        type: 'category',
        label: 'Diet',
        items: [
          'bryan/diet/overview',
          {
            type: 'category',
            label: 'Food',
            items: [
              'Reference/Recipes/green-giant',
              'Reference/Recipes/super-veggie',
              'Reference/Recipes/nutty-pudding',
            ],
          },
          {
            type: 'category',
            label: 'Supplements',
            items: [
              'Reference/Supplements/overview',
            ],
          },
        ],
      },
      {
        type: 'category',
        label: 'Fitness',
        items: [
          'bryan/fitness/overview',
        ],
      },
      {
        type: 'category',
        label: 'Measurements',
        items: [
          'bryan/measurements/overview',
          'bryan/measurements/biomarkers',
          'bryan/measurements/tests',
        ],
      },
    ],
  },
  reference: [
    {
      type: 'autogenerated',
      dirName: 'Reference', // The name of the directory in the 'docs' folder
    },
  ],
};

module.exports = sidebars;
